name: Build BIN Index

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore and build Analyzer
      run: dotnet build Analyzer.csproj

    - name: Run Analyzer to generate index.html
      run: dotnet run --project Analyzer.csproj

    - name: Upload index.html to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
