name: Build BIN Index

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build old-style C# Analyzer.csproj
      run: msbuild Analyzer/Analyzer.csproj /p:Configuration=Release

    - name: Run Analyzer.exe
      run: Analyzer\bin\Release\Analyzer.exe

    - name: Upload index.html to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./output

  deploy:
    needs: build
    runs-on: windows-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
